### ISSUE TITLE
First release checklist

### ISSUE THREAD

**Issue by phaer** [dep-sys/nix-dabei#14]
* [x] Updated README
* [x] Github workflow to publish Release
* [x] Example flake ready to enjoy
* [x] systemd service naming convention: 
> possibly sth like a common prefix (nix-dabei or auto-install) and a number for the step. makes filtering much easier - e.g. you can do a similar thing to systemctl list-units 'initrd*'.
* [x] full-terminal / pager
> log output is also truncated because less is not installed as a pager. adding --no-pager --full to each command makes the right behaviour. This could be added to the over systemd config to minimize.
* [x] #21 
* [x] #16 
* [ ] persistent installer logs

**Comment by dantefromhell** [comment]
re full-terminal / pager

`man journalctl` lists a range of environment variables towards the bottom to control behaviour - incl the pager.

**Comment by dantefromhell** [comment]
> full-terminal / pager

PR #20 tries to address this issue.
