### ISSUE TITLE
0-click provisioning on hetzner cloud

### ISSUE THREAD

**Issue by phaer** [dep-sys/nix-dabei#2]
As a first step, I'd like to support non-interactive deployment of NixOS on hetzner.cloud.

The general design will probably be similar to [my first appraoach](https://github.com/dep-sys/nixos-zfs-installer), especially [write-runtime-info.sh](https://github.com/dep-sys/nixos-zfs-installer/blob/main/installer/scripts/write-runtime-info.sh),  We might also incorporate some ideas from [@zhaofengli/install.sh](https://gist.github.com/zhaofengli/e986fa7688d6c16872b86c6ae6215c9b) to acquire host information directly from a [colmena](https://github.com/zhaofengli/colmena) config

## Tasks

* [ ] check that target host does not exist already
* [ ] create target host via hcloud api, start in rescue mode
* [ ] build & upload kexec image to target host
* [ ] gather runtime data like disk names and network interfaces from rescue system
* [ ] execute kexec-boot script on target host, pass runtime data via kernel cmdline
* [ ] partition disk(s) - single disk zfs as a first step
* [ ] write runtime-data onto newly formatted fs to read from activation script
* [ ] push target closure to target host, then reboot for clean slate.

## Possible follow-up issues
(to be sketched out after implementation)

* modularization: support a second provider (digital ocean, vultr, ...)
* support dedicated hetzner machines
