### ISSUE TITLE
tracking: zfs support

### ISSUE THREAD

**Issue by phaer** [dep-sys/nix-dabei#3]
This is a tracking issue, the idea is provide a quick overview and to create separate issues for each item if there's a need for discussing.

As both @dantefromhell and myself are interested in using ZFS as a file system, that one will be implemented first. Support for ext4, btrfs or bcachefs can be be implemented and tested whenever interest arises.

# Tasks

1. [X] ~add ZFS to nix-dabei~ #1
2. [x] implement an auto-partitioner for zfs-on root (single disk)
3. [ ] support mirroring of multiple disks in auto-partitioner
4. [ ] support custom partition layouts if feasible (research existing solutions)
5. [ ] support booting from encrypted zfs
6. [ ] support (document & test) [impermance](https://github.com/nix-community/impermanence) 
7. [ ] reduce closure size (samba, python, systemd are zfs dependencies by default)
