### ISSUE TITLE
add documentation infrastructure

### ISSUE THREAD

**Issue by phaer** [dep-sys/nix-dabei#4]
This still needs a bit of research; I am looking for a solution which allows us to write long-form documentation in markdown or org-mode format and to auto-generate references from source code & inline comments. 

Should be stable, easy to integrate into CI & easy to run locally.

One option would be to clone what [colmenas manual](https://github.com/zhaofengli/colmena/tree/main/manual) does with [mdBook](https://github.com/rust-lang/mdBook) and push its HTML output to github pages.

Another one would be to keep using markdown and to generate reference documentation for options like [i did here before](https://github.com/dep-sys/nix-dabei/commit/d3d1550c0fbc1bda9affd6d5e27998f2e7d6e015#diff-74ca1b180793b4453ff03ec4a05fa2bd831af1888a5112c681266bec65e0192e), but that's only for options.
An ideal solution should also allow use to document (some) functions via inline comments and to convert those to markdown/html.

Input & ideas welcome! :bulb: 

# Tasks

* [ ] document custom options
* [ ] cleanup flake.nix: we want to keep boilerplate here to a minimum as flake.nix should provide a quick and easy to parse overview.
* [ ] write walk-through for kexec deployment on hetzner cloud 
* [ ] finish FAQ comparisons in README

**Comment by yagehu** [comment]
I'm a fan of org-mode, but I don't use Emacs anymore. I know of this https://github.com/200ok-ch/organice but don't know how well it works as a documentation system. Just throwing in ideas. Markdown might be the easiest thing :p
