### ISSUE TITLE
tracking: closure size reduction

### ISSUE THREAD

**Issue by phaer** [dep-sys/nix-dabei#5]
Ideas, experiments & discussion to get the smallest image possible while still including essential tools to install and rescue nixos systems.

To investigate size-related questions I generally run 

```sh
nix build --json .#toplevel --no-link | jq -r '.[].outputs.out' | xargs -o nix-tree
```
before i press "s" once to sort by output size. "w" for "why-depends" is useful as well.

* [ ] kernel: we could probably build much smaller kernels for cloud hypervisors
* [ ] zfs: we should be able to get rid of most of it current dependencies like samba, systemd (not the same as our systemd-minimal), python, etc
* [ ] can we break the loop between utillinux and utilinuxMinimal and keep only on?
* [ ] can we do without squashfs? that's not really about size but could simplify the boot process
* [ ] why is man-db included?
* ...

**Comment by mlyxshi** [comment]
nix build has a new `--print-out-paths` flag to print the resulting output paths.
https://nixos.org/manual/nix/stable/release-notes/rl-2.9.html

I think we can remove jq and reduce initrd size
